window.STUDY_DAY = {
  "day": 1,
  "date": "2026-09-14",
  "course": "CS224N",
  "title": "Transformers",
  "subtitle": "Self-attention이 왜 필요한지부터 Transformer block 전체를 연결해 이해한다.",
  "systemPosition": "Foundation · LLM Backbone",
  "systemMapping": "긴 Evaluation Case와 공정 문맥을 처리하는 LLM의 내부 계산 구조를 이해하는 날이다. Attention weight 자체를 공정의 인과 설명으로 해석하지 않는다.",
  "progressKey": "stanford-study-day01-progress-v3",
  "pcFile": "day01_2026-09-14_pc.html",
  "mobileFile": "day01_2026-09-14_mobile.html",
  "sourceLinks": [
    {"label": "2026 Transformers 슬라이드", "url": "https://web.stanford.edu/class/cs224n/slides_w26/cs224n-2026-lecture05-transformers.pdf"},
    {"label": "Attention Is All You Need", "url": "https://arxiv.org/abs/1706.03762"}
  ],
  "modules": [
    {"sourceLabel":"Lecture Section · Why Attention","title":"왜 Attention이 등장했나","core":["RNN 계열의 순차 계산은 먼 token 사이의 정보 전달 경로가 길다.","Self-attention은 모든 token 쌍의 상호작용을 한 층에서 직접 계산할 수 있다.","병렬화 가능성은 Transformer가 대규모 학습에 적합해진 중요한 이유다."],"easy":"긴 문장을 사람에게 한 단어씩만 보여주고 앞 단어를 머릿속에 기억하게 하면 뒤로 갈수록 처음 정보가 희미해진다. Self-attention은 문장 전체를 책상 위에 펼쳐두고, 현재 token이 필요한 다른 token을 바로 가리킬 수 있게 만든 방식에 가깝다.","professor":"강의 흐름에서 Attention은 단순히 성능이 좋은 새 layer로 나오지 않는다. 먼저 순차 모델의 병목과 장거리 dependency 문제를 확인한 다음, 정보가 지나가는 경로를 짧게 만들자는 아이디어로 넘어간다. 이 관점을 잡아야 다음의 Q/K/V 수식이 왜 필요한지 이해된다. 수식은 목적이 아니라 어떤 token을 얼마나 참고할지를 미분 가능한 계산으로 만든 결과다.","practical":"Recipe Advisor가 긴 Evaluation Case 여러 건과 현재 context를 한 prompt에서 처리할 때도 모델 내부에서는 이런 token 상호작용이 일어난다. 다만 attention map이 특정 recipe parameter와 metric의 실제 인과관계를 증명해 주는 것은 아니다. 공정 근거는 Process Memory의 evidence/provenance와 별도로 검증해야 한다.","terms":[["Long-range dependency","멀리 떨어진 정보 사이의 의존성"],["Path length","두 token의 정보가 서로 영향을 주기까지 거치는 계산 단계 수"],["Parallelism","여러 token 위치의 계산을 동시에 수행할 수 있는 성질"]],"quiz":[["RNN보다 self-attention이 장거리 관계를 다루기 쉬운 직관은?","두 token 사이의 정보 전달 경로가 짧고 직접적이기 때문이다."],["Attention weight를 공정 인과관계로 바로 해석하면 안 되는 이유는?","학습된 representation의 가중합 계수이지 실험적 인과 증거가 아니기 때문이다."]] },
    {"sourceLabel":"Lecture Section · Q/K/V","title":"Q, K, V와 Scaled Dot-Product Attention","core":["Query는 현재 위치가 찾는 정보의 기준, Key는 각 위치가 제공하는 매칭 기준, Value는 실제 가져올 내용이다.","QKᵀ 점수에 softmax를 적용해 Value의 가중합을 만든다.","√dₖ scaling은 차원이 커질 때 dot product가 과도하게 커져 softmax가 포화되는 것을 완화한다."],"easy":"도서관 검색으로 비유하면 Query는 내가 찾는 질문, Key는 각 책의 색인 카드, Value는 책의 실제 내용이다. 질문과 색인이 잘 맞을수록 그 책의 내용이 더 많이 섞여 현재 token의 새 표현이 된다.","professor":"교수는 보통 Q/K/V를 외우라고 하기보다 행렬 shape를 따라가게 한다. token 수가 n이고 head 차원이 d라면 QKᵀ는 n×n 관계 행렬이 된다. 여기서 중요한 것은 n² 비용과 softmax 전의 scale이다. 다음 multi-head로 넘어가는 이유도 하나의 similarity 공간만으로 모든 관계를 표현하기보다 여러 projection 공간을 병렬로 두기 위해서다.","practical":"긴 공정 context를 넣으면 n² attention 비용이 커진다. 그래서 Recipe Advisor에서는 DB 결과를 많이 가져오면 모델이 알아서 보겠지가 위험하다. retrieval top-k, Context Builder 요약, 필요한 evidence만 포함하는 column/row pruning이 모델 품질뿐 아니라 inference cost에도 직접 연결된다.","terms":[["Query","현재 token이 찾고 싶은 정보의 projection"],["Key","다른 token과 매칭할 때 쓰는 projection"],["Value","매칭 후 실제 집계되는 정보"],["Scaled dot-product attention","QKᵀ/√dₖ를 softmax한 뒤 V를 가중합하는 연산"]],"quiz":[["√dₖ로 나누는 이유는?","dot product 분산이 커져 softmax가 포화되는 현상을 줄이기 위해서다."],["QKᵀ의 크기가 n×n이라는 사실이 실무에서 의미하는 것은?","sequence가 길어질수록 attention 계산/메모리가 대략 제곱으로 증가한다는 뜻이다."]] },
    {"sourceLabel":"Lecture Section · Multi-Head","title":"Multi-Head Attention","core":["여러 head는 서로 다른 learned projection 공간에서 attention을 계산한다.","head의 의미가 사람에게 명확한 문법 head/의미 head로 고정된다고 가정하면 안 된다.","head 결과를 concatenate한 뒤 다시 projection하여 다음 block으로 넘긴다."],"easy":"한 명의 전문가가 모든 관점으로 문서를 읽는 대신 여러 사람이 각자 다른 렌즈로 읽고 의견을 합치는 것과 비슷하다. 중요한 점은 각 사람이 어떤 역할을 맡는지 미리 이름 붙이지 않는다는 것이다. 학습 과정에서 유용한 분해가 형성된다.","professor":"단일 attention을 이해한 뒤 multi-head가 나오는 이유는 관계가 하나뿐이지 않다는 문제 때문이다. 같은 token 쌍도 구문적·담화적·참조적 관계 등 여러 방식으로 상호작용할 수 있다. 다만 특정 head 하나에 인간 친화적 의미를 강제로 부여하는 해석은 불안정할 수 있다는 점도 함께 기억해야 한다.","practical":"Process Memory에서 여러 evidence가 서로 다른 관계를 가질 수 있지만, multi-head attention을 FDC head, Recipe head처럼 임의로 해석할 필요는 없다. 실제 시스템 설계에서는 입력 schema와 retrieval filter를 명시적으로 분리하고, 모델 내부 head는 내부 표현 학습으로 남겨두는 편이 안전하다.","terms":[["Attention head","별도 Q/K/V projection을 가진 attention 경로"],["Concatenation","여러 head 출력을 feature 차원으로 이어 붙이는 연산"],["Projection","학습 가능한 선형 변환으로 표현 공간을 바꾸는 연산"]],"quiz":[["Multi-head가 단일 attention보다 주는 핵심 자유도는?","서로 다른 projection 공간에서 관계를 동시에 학습할 수 있다."],["각 head에 사람이 이해하는 고정 역할을 붙이면 위험한 이유는?","head의 기능은 학습과 모델에 따라 분산되고 바뀔 수 있기 때문이다."]] },
    {"sourceLabel":"Lecture Section · Causality & Position","title":"Causal Mask와 Positional Information","core":["Autoregressive LM은 다음 token을 예측할 때 미래 token을 볼 수 없어야 한다.","Causal mask는 attention score에서 미래 위치를 차단해 정보 누설을 막는다.","Self-attention 자체는 순서를 모르므로 positional information이 필요하다."],"easy":"시험 문제의 정답을 뒤 페이지에 써놓고 앞 문제를 풀 때 그 페이지를 못 보게 가리는 것이 causal mask다. 또 단어들을 카드처럼 한꺼번에 놓으면 순서 정보가 사라지므로, 각 카드에 몇 번째 위치인지를 알려주는 장치가 positional encoding이다.","professor":"이 부분은 Transformer가 단순 set processor가 아니라 language model이 되기 위한 두 제약을 설명한다. 첫째는 학습 시 미래 정보 leakage를 막는 것, 둘째는 순서를 표현하는 것이다. 이후 긴 context와 position extrapolation 문제를 이해할 때도 이 두 개념이 다시 등장한다.","practical":"공정 데이터에서는 시간 순서가 중요하다고 해서 LLM causal mask가 자동으로 공정 causality를 보장하는 것은 아니다. 공정 event ordering은 Context Builder가 timestamp/step sequence를 정확히 구성해야 하며, 모델 mask는 token prediction의 정보 누설만 제어한다.","terms":[["Causal mask","미래 token으로 향하는 attention을 차단하는 mask"],["Autoregressive","이전 token을 조건으로 다음 token을 순차 생성하는 방식"],["Positional encoding","token의 순서/위치 정보를 표현에 주입하는 방법"]],"quiz":[["Causal mask가 막는 leakage는 무엇인가?","다음 token 예측 중 정답이 되는 미래 token을 미리 보는 leakage다."],["Self-attention에 positional information이 필요한 이유는?","attention 연산만으로는 입력 순서를 구별할 수 없기 때문이다."]] },
    {"sourceLabel":"Lecture Section · Transformer Block","title":"Residual, LayerNorm, MLP와 전체 Block","core":["Attention만으로 Transformer가 완성되는 것이 아니라 residual path, normalization, position-wise MLP가 반복된다.","Residual connection은 정보와 gradient가 깊은 network를 통과할 경로를 제공한다.","MLP는 token별 비선형 feature 변환을 담당하고 attention과 상보적이다."],"easy":"Attention이 다른 token에서 어떤 정보를 가져올지 결정한다면 MLP는 가져온 정보를 각 위치에서 어떻게 가공할지 담당한다고 보면 쉽다. Residual은 원래 정보가 매 block을 지날 때 완전히 덮어써지지 않도록 우회도로를 둔다.","professor":"강의의 마지막에는 개별 수식을 하나의 반복 block으로 조립한다. 여기서 중요한 mental model은 attention과 MLP가 번갈아 representation을 갱신하고 residual stream이 block 전체를 관통한다는 점이다. 다음 pretraining 강의로 넘어가면 이 architecture가 어떤 objective와 대규모 data로 실제 능력을 얻는지 보게 된다.","practical":"Recipe Advisor 관점에서 architecture 자체를 바꾸는 것보다 더 중요한 경우가 많다. Context Builder, retrieval, evidence schema가 나쁘면 강한 Transformer도 잘못된 문맥을 정교하게 처리할 뿐이다. 오늘은 모델 내부가 무엇을 할 수 있는가를 이해하고, 이후에는 무엇을 입력해야 하는가로 넘어간다.","terms":[["Residual connection","입력을 변환 결과에 더해 정보/gradient 경로를 유지하는 연결"],["LayerNorm","feature scale을 안정화하는 normalization"],["Feed-forward/MLP","각 token 위치에서 독립적으로 적용되는 비선형 변환"]],"quiz":[["Attention과 MLP의 역할 차이를 한 문장으로 말하면?","Attention은 token 간 정보 교환, MLP는 각 token representation의 비선형 가공을 주로 담당한다."],["Day 1에서 Day 2 Pretraining으로 넘어가는 논리는?","architecture를 이해했으니 이제 그 architecture가 어떤 data/objective로 능력을 획득하는지 보기 위해서다."]] }
  ]
};